query GetMe {
  getMe {
    id
    username
    email
    password

    isVerified
    isEmailVerified
    isTotpEnabled
    totpSecret

    deactivatedAt
    isDeactivated

    createdAt
    updatedAt
  }
}
