export const socialIcons: Record<string, string> = {
  "google.com": "simple-icons:google",
  "github.com": "simple-icons:github",
  "youtube.com": "simple-icons:youtube",
  "youtu.be": "simple-icons:youtube",
  "twitch.tv": "simple-icons:twitch",
  "kick.com": "simple-icons:kick",
  "x.com": "simple-icons:x",
  "twitter.com": "simple-icons:x",
  "facebook.com": "simple-icons:facebook",
  "instagram.com": "simple-icons:instagram",
  "threads.net": "simple-icons:threads",
  "linkedin.com": "simple-icons:linkedin",
  "reddit.com": "simple-icons:reddit",
  "tiktok.com": "simple-icons:tiktok",
  "discord.com": "simple-icons:discord",
  "discord.gg": "simple-icons:discord",
  "telegram.org": "simple-icons:telegram",
  "t.me": "simple-icons:telegram",
  "whatsapp.com": "simple-icons:whatsapp",
  "spotify.com": "simple-icons:spotify",
  "figma.com": "simple-icons:figma",
  "vk.com": "simple-icons:vk",
  "rutube.ru": "simple-icons:rutube",
  "boosty.to": "simple-icons:boosty"
}
