query FindChannelByUsername($username: String!) {
  findChannelByUsername(username: $username) {
    id
    username
    email
    password

    avatar
    bio

    isNotificationsEnabled

    isVerified
    isEmailVerified

    sponsorshipPlans {
      id
      title
      description
      price
    }

    followings {
      id
    }

    socialLinks {
      id
      title
      url
    }

    stream {
      id
      title
      thumbnailUrl
      isLive
      chatMode

      category {
        id
        title
        slug
        description
      }
    }

    createdAt
    updatedAt
  }
}
