query GetUser {
  getUser {
    id
    username
    email
    password

    avatar
    bio

    isVerified
    isEmailVerified
    isNotificationsEnabled

    socialLinks {
      id
      title
      url
    }

    stream {
      id
      serverUrl
      streamKey
      chatMode
    }

    notifications {
      id
      payload
      isRead
      type
    }

    createdAt
    updatedAt
  }
}
