query FindCategoryBySlug($slug: String!) {
  findCategoryBySlug(slug: $slug) {
    id
    title
    slug
    thumbnailUrl
    description

    streams {
      id
      title
      thumbnailUrl
      isLive

      chatMode

      user {
        username
        avatar
        isVerified
      }

      category {
        id
        title
        slug
      }
    }
  }
}
